import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./all-animation.css";
import 'bootstrap/dist/css/bootstrap.min.css';
declare module 'bootstrap/dist/js/bootstrap.bundle.min.js';
import Header from "./pages/header";
import { motion, AnimatePresence } from "framer-motion";
import { ThemeProvider } from "next-themes";
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import { Toaster } from "react-hot-toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jainsy Anjirwala",
  description: "Generated by Jainsy Anjirwala",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >  <AnimatePresence mode="wait">
        </AnimatePresence>
          <Header />
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
